### ISSUE TITLE
cleanup FE issues

### ISSUE THREAD

**Issue by robert-weissgraeber** [letsmeet-click/letsmeet.click#10]
- [ ] minify JS/CSS and put into 1 file each (currently ~15) (maybe just use cloudflare with auto option)
- [ ] configure browser caching
- [ ] social icons (twitter/facebook) are blocking page load  (use e.g. https://github.com/kni-labs/rrssb)
- [ ] header image on startpage is too big

**Comment by asmaps** [comment]
- [x] Menu broken on mobile (references #13)
