### ISSUE TITLE
privacy concern: google analytics tracking

### ISSUE THREAD

**Issue by summerjob** [letsmeet-click/letsmeet.click#17]
please remove google analytics tracking
there are more privacy aware tracking solutions out there, e.g. piwik.org which can also run self-hosted

**Comment by ThomasWaldmann** [comment]
+1

**Comment by robert-weissgraeber** [comment]
we are currently not able to sustainably implement a self-hosted solution. we will revisit this, when we have a more manpower. if you want to contribute, we would be happy to support you.

**Comment by asmaps** [comment]
Use things like https://www.ghostery.com/ if you do not want to be tracked.

**Comment by ThomasWaldmann** [comment]
please reopen. existance of tools to avoid tracking is no excuse to track people.

**Comment by mblaschke** [comment]
:+1:
