### ISSUE TITLE
privacy concerns: twitter and facebook

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsmeet-click/letsmeet.click#18]
there are twitter and facebook buttons and it seems they are loaded from their servers.

replace this with a more privacy compatible solution, see e.g.:
http://www.heise.de/ct/ausgabe/2014-26-Social-Media-Buttons-datenschutzkonform-nutzen-2463330.html ("shariff").

**Comment by asmaps** [comment]
Use https://www.ghostery.com/ if you do not like to be tracked by those things

**Comment by ThomasWaldmann** [comment]
please reopen. existance of tools to avoid tracking is no excuse to track people.
