### ISSUE TITLE
think about removing communities

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsmeet-click/letsmeet.click#38]
it's easy to add one, which will lead to lots of communities soon.

it will also lead to lots of testing / stale communities that show up in the main list, like "anarcat-test", "Foo", etc.

to avoid accumulating crap, there should be some procedure to remove a community (and this should be possible not just for the founder or admin).

**Comment by mfa** [comment]
the problem is deletion of communities with events. deletion will remove the history of this community.

for now we plan to remove stale and obvious testing communities after a few days via the admin interface.

**Comment by NotANormalNerd** [comment]
Then just deactivate the community for now and don't show those communities in the UI.
They are still there and can easily be recovered, but are "deleted"

**Comment by robert-weissgraeber** [comment]
will be solved by general UI rework, after we have a significant amount of users, usage and events.
