### ISSUE TITLE
quality requirements

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsmeet-click/letsmeet.click#39]
besides the (testing) entries which are obviously crap, there are some which do not contain enough information.

e.g. empty description and/or no homepage link.

**Comment by mfa** [comment]
that is the problem of the owner of the community.
maybe they have no homepage, or don't want to describe themselves.

**Comment by ThomasWaldmann** [comment]
well, filling the main page with a lot of crap is a problem for every user of the system.
you click through all these "communities" and you don't get any further information.
if not telling anything is a wanted feature, i suggest creation of private communities (which do not show up in the main list).

**Comment by asmaps** [comment]
There will be some improvements to this when #28 is done. Filtering/Sorting/whatever of communities will only make sense when there are some more. now you can only guess which are criteria for "good" ones, so there will also be some improvement but at a later point.
