### ISSUE TITLE
add "active communities"

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsmeet-click/letsmeet.click#40]
there's "all c." and "your c." in the sidebar navigation, but "active c." would be useful also.

active = "has an upcoming event" (maybe also: "had an event in last N days")

**Comment by asmaps** [comment]
as stated in #39 things like this will be done at a later point

**Comment by robert-weissgraeber** [comment]
will be solved by general UI issues, additionally: after a significant amount of usage has been achived, the noise/signal ration due to test-communities/-events will vanish.
