### ISSUE TITLE
Please send notifies to bcc: not to to:

### ISSUE THREAD

**Issue by TabTwo** [letsmeet-click/letsmeet.click#44]
"[letsmeet.click] New comment for Erstes #SchnitzelS in 2016" -> every recipient is in the to: header.
Every virus which harvests addresses says thank you.

**Comment by asmaps** [comment]
Yes, I also just noticed this... will fix this

**Comment by asmaps** [comment]
should be fixed. please tell us if you find some mail where it's still broken.
