### ISSUE TITLE
shorten Links

### ISSUE THREAD

**Issue by TabTwo** [letsmeet-click/letsmeet.click#49]
not sure for how many events you're planning ... but this:
http://email.letsmeet.click/c/eJxVTsEKwyAU-5p6U572ae3Bwy77D6tPKmvLUEdZv37uWEgICSEkOqNj8Cw7BdKAkpOSaACFVRK0kGaGAWGjVneiJsKWw4utTvqEk15CF4uTH_WMYyBrFCRIiMg2t7b2rsP4GNSz4zxPcV_pYeisYT1yu2irN8PzzhMt5eML_z_joLi0vcKKK7v_Uum3DiqRF6o50nGJSD_z7j8l
is overkill.

Thanks!

**Comment by mfa** [comment]
the links are generated by mailgun. not by us.
