### ISSUE TITLE
Be able to join a community on event view..

### ISSUE THREAD

**Issue by mpathy** [letsmeet-click/letsmeet.click#5]
When I get a link to an event for somebody, and I am not in the associated community, it would be great to be able to join the community on this page already - instead of searching it in the community list and then get back to the specific event page and join then.

**Comment by robert-weissgraeber** [comment]
+1

maybe just auto-join community on event subscribtions, user can de-join community later

**Comment by asmaps** [comment]
@mpathy you can use the button "Back to community" quickly get to the community

**Comment by robert-weissgraeber** [comment]
@asmaps the main usecase is an event-specific messagge on another platfform (twitter, G+) -> joining with 1 click would be the most easiest way.

**Comment by asmaps** [comment]
Sure, I see the need for this. The suggestion was the current "workaround"
