### ISSUE TITLE
Unable to edit own events

### ISSUE THREAD

**Issue by makefu** [letsmeet-click/letsmeet.click#65]
For some reason i cannot edit the events i've created myself. Login via gitlab.
Edit via admin interface is working
![](https://screenshotscdn.firefoxusercontent.com/images/8d046cdb-bc78-4a2f-8922-6a2d80483c1f.png?download=Screenshot-2018-3-12%20Change%20user%20Django%20site%20admin.png&sig=eALXJjjB94vhRFZR_UOt62tw7ug)

**Comment by powerriegel** [comment]
Related to #68

**Comment by powerriegel** [comment]
#68 is closed. Please close this, too.
