### ISSUE TITLE
Editing function disappeared

### ISSUE THREAD

**Issue by robingarcia** [letsmeet-click/letsmeet.click#68]
It is not possible to edit own events and contributions.

**Comment by robingarcia** [comment]
Now issue 67 is back. 
https://github.com/letsmeet-click/letsmeet.click/issues/67

**Comment by mfa** [comment]
I reviewed all permissions, improved some code. should work now.

**Comment by mfa** [comment]
please logout/login, if problem still persists and try again.

**Comment by robingarcia** [comment]
Yes. It works now. Thanks for solving the problem.
