### ISSUE TITLE
Admins can set Owners to Admin

### ISSUE THREAD

**Issue by powerriegel** [letsmeet-click/letsmeet.click#69]
If a community has 1 admin and 1 owner, the admin can downgrade the owner to an admin. There is no more owner then. 

Expected behavior: There should be a check if there is at least one owner remaining.

**Comment by robingarcia** [comment]
I lost the my owner status in my group https://www.letsmeet.click/c/jugru-stuttgart/
because I was downgraded by an admin to admin. Now my group has no owner anymore and the admin is not able to edit the group etc. -.-

**Comment by mfa** [comment]
you are owner now.

**Comment by robingarcia** [comment]
But I can't edit. Even I am owner. Why? 
Once I logged in with my twitter acc @the_necrosis
But then I logged in with Github as robingarcia. 
But In letsmeet I was recognized as the_necrosis. Therfore I need to be owner with "the_necrosis". 
I know this is a little bit confusing. :-/
