### ISSUE TITLE
send event to calendar

### ISSUE THREAD

**Issue by mpathy** [letsmeet-click/letsmeet.click#7]
It would be nice to send the event date to a calendar - most popular maybe: send to google calendar - to keep track of it.

Alternatively, send an email to the mail adress of the user with an ics file.. modern webmailers and mail programs can automatically create an calendar entry when such a mail gets into the inbox.

**Comment by mblaschke** [comment]
:+1:

**Comment by asmaps** [comment]
I have already thought about an ical link for your subscribed events, so you can just import it from calendar apps

**Comment by robert-weissgraeber** [comment]
+1 for ics file download

**Comment by TabTwo** [comment]
one feed per community, one personal feed for my upcoming events, one for all events that I attend

**Comment by asmaps** [comment]
@TabTwo  sounds good :-)

**Comment by cornz** [comment]
maybe just implement this to generate the ical feed/file from the rss feed: 
https://github.com/dsanvita/feed2ical

looks fine and is not outside of universe.py ;)

**Comment by mfa** [comment]
ical support added.
